### ISSUE TITLE
Homepage lead carousel

### ISSUE THREAD

**Issue by halfempty** [everythingtype/calcott#48]
I've begun on this. But not finished.

**Comment by ncalcott** [comment]
OK, noted.  Seems to function pretty well, though.

**Comment by halfempty** [comment]
@ncalcott I've added some fields to the Edit screen of the Carousel page. When you get a chance, will you populate these with captions and links?

**Comment by ncalcott** [comment]
Sure, will do. 

Can we add the 'News' page or some way to link to it into the associated portfolio dropdown somewhere?  I may end up using this carousel to post recent work, in which case I'll want to just link to that category page as I won't have posted a portfolio yet....

**Comment by halfempty** [comment]
@ncalcott Would it be better if that field was an open URL field, so that you could link to anything? If so, I will change it right now

**Comment by ncalcott** [comment]
I dunno if it'd be better, but if it's easier and will save some dev time it's not a major functionality issue for me - so, sure, go for it.  Thanks!

**Comment by halfempty** [comment]
@ncalcott Okay, fieldset updated

**Comment by ncalcott** [comment]
Hey all (@halfempty, @KyleETC, @gehalber)-

For the carousel, what do you guys think about having the left/right arrows disappear and are only visible on rollover? 

Seeing as the site's about showing images, I'd prefer to keep them as uncluttered as possible.  Obviously, if we do this, we'd have to make the rollover area quite a bit larger than just immediately over the arrows...

**Comment by ncalcott** [comment]
Also, wouldn't mind returning the 'close window x' to the news box, so a viewer can make it disappear if they just want to see the image in the carousel.  I don't really mind if the only way they can bring it back is to reload the page - chances are they don't need the info anymore, and the natural ux if they do would be to click on 'News', which will take them to the full archive...

**Comment by ncalcott** [comment]
Sorry, another minor thing - can we set the images to show up in random order?  I know it's counter-intuitive (given that I have the ability to edit the image order on the backend), but I'd love the site to always feel fresh whenever someone visits, and I don't really have the patience to revisit the site frequently just to change the front page order...

**Comment by halfempty** [comment]
@ncalcott Random order: Check!

**Comment by ncalcott** [comment]
@halfempty - I'm hoping to do an e-mail blast in the first week of September.  I realize there's still a few things to get to, but any chance we could have the captions on the carousel show up and the arrows only show on hover before then?  I'd also love to fix the updates module (issue #51) before then too...

**Comment by ncalcott** [comment]
I added in the caption fields that hadn't been implemented yet and changed them to WSIYG editors in the Custom Fields plugin.  Also, I modified the opacity of the backgrounds of the next/prev buttons.  These are meant as temporary fixes, of course...

**Comment by ncalcott** [comment]
One issue with the way I've implemented this is that the captions are floating at the bottom of the window and not directly below the image itself, contrary to the original design.  This isn't intentional - I just didn't have time to rejigger the CSS to get it to work as intended...

**Comment by halfempty** [comment]
@ncalcott @gehalber I've done some additional caption jiggering:

![image](https://cloud.githubusercontent.com/assets/775543/18567593/7d70def8-7b5e-11e6-972c-0c5bb254c990.png)

**Comment by ncalcott** [comment]
Hey hey - looks good.  Thing is, the images have disappeared in the carousel when viewing on safari in non-mobile view (the work in the reduced width css)...
![screen shot 2016-09-16 at 11 06 59 am](https://cloud.githubusercontent.com/assets/7586166/18590800/33693cec-7bfe-11e6-8cb1-144e6dfba426.png)

**Comment by halfempty** [comment]
@ncalcott Hmm. Working on my end. I've updated the version number, in case it's a cache issue. Can you confirm that it's still happening? Thanks!

**Comment by halfempty** [comment]
Question for @gehalber and @KyleETC --

In the mockup I'm seeing a couple of different treatments of the arrows. Which one should I be looking at?

Arrows as buttons:
![image](https://cloud.githubusercontent.com/assets/775543/18769458/d961d2b4-80f2-11e6-9fe5-1540a42cd124.png)

Or arrows as cursors:
![image](https://cloud.githubusercontent.com/assets/775543/18769463/e4ac7340-80f2-11e6-8391-44517573b1eb.png)

**Comment by gehalber** [comment]
Arrows as buttons

**Comment by halfempty** [comment]
@gehalber Okay, buttons updated! Closing this...
